# Generated by Django 2.1.7 on 2019-03-21 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksmg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('gubun', models.CharField(choices=[('1', '제품/재료 개발 지원'), ('2', '불량 분석/개선'), ('3', '공정 개선'), ('4', '품질 개선'), ('5', '해석/분석/평가 지원'), ('6', '고객 대응 지원'), ('7', '기타')], max_length=1)),
                ('detail', models.CharField(max_length=4000)),
                ('expect_effect_asis', models.CharField(max_length=4000)),
                ('expect_effect_tobe', models.CharField(max_length=4000)),
                ('request_confirm', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('request_confirm_detail', models.CharField(max_length=4000)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('next_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksmg_next_user', to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksmg_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KsmgEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2019)),
                ('sales', models.IntegerField()),
                ('cost_save', models.IntegerField()),
                ('productivity', models.CharField(max_length=1000)),
                ('quality', models.CharField(max_length=1000)),
                ('etc', models.CharField(max_length=1000)),
                ('ksmg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksmg.Ksmg', verbose_name='related Ksmg')),
            ],
        ),
    ]
