# Generated by Django 2.1.7 on 2019-03-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksmg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksmg',
            name='gubun',
            field=models.CharField(choices=[('제품/재료 개발 지원', '제품/재료 개발 지원'), ('불량 분석/개선', '불량 분석/개선'), ('공정 개선', '공정 개선'), ('품질 개선', '품질 개선'), ('해석/분석/평가 지원', '해석/분석/평가 지원'), ('고객 대응 지원', '고객 대응 지원'), ('기타', '기타')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ksmg',
            name='request_confirm',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=10),
        ),
    ]
