# Generated by Django 2.1.7 on 2019-03-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksmg', '0002_auto_20190321_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksmgee',
            name='ksmg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksmgee', to='ksmg.Ksmg'),
        ),
    ]
