# Generated by Django 2.1.7 on 2019-03-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksmg', '0003_auto_20190321_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksmgee',
            options={'ordering': ['year']},
        ),
    ]
